### ISSUE TITLE
Preserve environment when calling scripts

### ISSUE THREAD

**Issue by paullexen** [maccyber/micro-dockerhub-hook#25]
Currently the runScript function creates a fresh environment with only the `TAG` and `REPO_NAME` variables. It would be nice if it would instead use the current `process.env` and just add those extra variables to it. That way useful variables such as `PATH` will be accessible to deployment scripts.

**Comment by maccyber** [comment]
Sorry for the late reply.
It sounds like a good idea, do you have the opportunity to send a pull request?
