### ISSUE TITLE
documentation bug token vs. TOKEN

### ISSUE THREAD

**Issue by tobiasneumann42** [maccyber/micro-dockerhub-hook#32]
the documentation states to run the docker container with 
docker run -d \
  -p 3000:3000 \
  -e TOKEN=**${token}** \
  -v ${PWD}/scripts:/src/scripts \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name micro-dockerhub-hook \
  maccyber/micro-dockerhub-hook

while the token is set in the shell with TOKEN= 

doesn't work as $token will be empty

**Comment by maccyber** [comment]
Thanks for noticing
